services:
  api:
    build:
      context: .
      target: dev-envs
    container_name: docker_api
    environment:
      PORT: 8088
    ports:
      - '8088:8888'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "no"
